// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDumZKZRTUqVGkydVpIJ7GI50WlP5tuh-Q',
    appId: '1:128139547714:web:2680fee7bf419bc30d49db',
    messagingSenderId: '128139547714',
    projectId: 'fir-chat-package',
    authDomain: 'fir-chat-package.firebaseapp.com',
    storageBucket: 'fir-chat-package.appspot.com',
    measurementId: 'G-KBVHPBHCTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZ0Lr3CKw-JWu_uLKpNkjyN4Npw3AROg',
    appId: '1:128139547714:android:222928a3544ff9dc0d49db',
    messagingSenderId: '128139547714',
    projectId: 'fir-chat-package',
    storageBucket: 'fir-chat-package.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMNZF8_XPtnK2du6LgpgtAi2sR1y9QHVM',
    appId: '1:128139547714:ios:a2c0feaa34aea68e0d49db',
    messagingSenderId: '128139547714',
    projectId: 'fir-chat-package',
    storageBucket: 'fir-chat-package.appspot.com',
    iosBundleId: 'com.example.firebaseChatPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMNZF8_XPtnK2du6LgpgtAi2sR1y9QHVM',
    appId: '1:128139547714:ios:ae5724b5b181ee3c0d49db',
    messagingSenderId: '128139547714',
    projectId: 'fir-chat-package',
    storageBucket: 'fir-chat-package.appspot.com',
    iosBundleId: 'com.example.firebaseChatPackage.RunnerTests',
  );
}
